version: '3.9'

services:
    wordpress:
          build: .
          container_name: wordpress_env
          restart: always
          ports:
                  - "8080:80"
          environment:
                  WORDPRESS_DB_HOST: db
                  WORDPRESS_DB_USER: wpuser
                  WORDPRESS_DB_PASSWORD: wppassword
                  WORDPRESS_DB_NAME: wpdb
          networks:
                  - wpnet
          volumes:
                  - ./wp_data:/var/www/html

    db:
          image: mysql:5.7
          container_name: wordpress_db
          restart: always
          environment:
                  MYSQL_DATABASE: wpdb
                  MYSQL_USER: wpuser
                  MYSQL_PASSWORD: wppassword
                  MYSQL_ROOT_PASSWORD: rootpassword
          volumes:
                  - ./db_data:/var/lib/mysql
          networks:
                  - wpnet

volumes:
    wp_data:
    db_data:
networks:
    wpnet:
